echo "This is my git hub project"
echo "My git hub project is running on `hostname`"
echo "Todays date is `date`"
echo "Sucessfully complete webhooks practical"
echo"Hi....."
echo "Sucessfully complete webhooks practical .."
